filename = input("Enter file name:")
f = open(filename)
lines=f.readlines()
count=len(lines)
characters = len(''.join(lines))
#f.seek(0)
#characters=len(f.read())
f.close()
print ("File",filename,"has",count,"lines and",characters,"characters.")
